### ISSUE TITLE
Plot multiple packages

### ISSUE THREAD

**Issue by FranklinYu** [archlinux-de/pkgstats.archlinux.de#107]
URL could be something like https://pkgstats.archlinux.de/packages/fish,zsh (comma-delimited list of packages), with some hard limit (e.g. 10 packages). It can be interesting to compare popularity of packages.

**Comment by pierres** [comment]
You can compare multiple packages by building an URL like https://pkgstats.archlinux.de/compare/packages#packages=fish,zsh It's not documented but does this fit what you were looking for?

**Comment by FranklinYu** [comment]
Yes, this is exactly what I was looking for. Any concern of documenting this? Or maybe even better, add a web form to generate this link?

**Comment by m1rm** [comment]
I am on it (a frontend form/something for this feature)
