### ISSUE TITLE
Rework fun statistics and provide sub pages

### ISSUE THREAD

**Issue by pierres** [archlinux-de/pkgstats.archlinux.de#132]

**Comment by m1rm** [comment]
merge into main with https://github.com/archlinux-de/pkgstats.archlinux.de/commit/44ad8da652495f78bce09af7507cc54841936960

**Comment by m1rm** [comment]
merge into main with https://github.com/archlinux-de/pkgstats.archlinux.de/commit/44ad8da652495f78bce09af7507cc54841936960
