### ISSUE TITLE
some "fun" categories needs some changes

### ISSUE THREAD

**Issue by Tids** [archlinux-de/pkgstats.archlinux.de#42]
I think we/you should add some more packages to some of the /fun groups.
###### Window Managers
  * sway (counts in at 7.26% rn)

###### Graphic Chipsets
As wayland compositors be more and more a thing, you'll not see that much of a xf86-video usage anymore, because its not used. xwayland also will just use the default modesettings. So for many users there is no need to even install them. So to have a group where you compare them, it might look like intel/amd are declining, while thats not true.

**Comment by pierres** [comment]
Thank you for your input.

1. I have added sway to window managers
2. I have renamed graphic chipsets to xorg drivers as we are only looking at installed packages and not actual hardware usage.
