### ISSUE TITLE
Server rejects non x86 archs submissions

### ISSUE THREAD

**Issue by ruifm** [archlinux-de/pkgstats.archlinux.de#46]
I have several archlinux machines, some of them in raspberry pis (using archlinuxarm) and I noticed the `pkgstats` systemd unit started failing about 1 week ago.

I did some investigation and discovered this only happens in archlinuxarm, not on regular `x86` archlinux.

On `archlinuxarm`, `pkglist submit` fails with:

```
Error: Server Error:{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":400,"detail":"Bad Request"}
```

I investigated further to find out why and figured out that the `POST` request gets rejected if `system.architecture` and `os.architecture` in the json data package are not **both** equal to `"x86_64"`.

By changing these fields in the POST request, this works on `archlinuxarm`:

```bash
curl --header "Content-Type: application/json" --request POST --data "$(pkgstats submit -d | jq '. | .system.architecture="x86_64" | .os.architecture="x86_64"')" 'https://pkgstats.archlinux.de/api/submit'
```

Is there a particular reason why you guys on server side started rejecting non-x86 submissions? Or was it just some kind of mistake?

**Comment by pierres** [comment]
Architectures other than x86_64 (and i686 some years ago) were never accepted. Earlier pkgstats version probably did not report the error though.

However I am thinking about supporting additional architectures as well: https://lists.archlinux.org/pipermail/arch-dev-public/2021-March/030378.html

**Comment by ruifm** [comment]
> Architectures other than x86_64 (and i686 some years ago) were never accepted. Earlier pkgstats version probably did not report the error though.

Then should we tell archlinuxarm maintainers that it does no longer make sense for them to provide [pkgstats](https://archlinuxarm.org/packages/aarch64/pkgstats) in their official repos? At least while that is the case, I don't know if you have a time window on that.

> However I am thinking about supporting additional architectures as well: https://lists.archlinux.org/pipermail/arch-dev-public/2021-March/030378.html

That is great! :1st_place_medal:

**Comment by pierres** [comment]
--I'll add ARM support soon. The server side part is easy, but I need to release a client that works correctly on ARM. A first testing release should be available this weekend.
