### ISSUE TITLE
​/api​/packages​: giving 00 as month results in wrong response

### ISSUE THREAD

**Issue by nsajko** [archlinux-de/pkgstats.archlinux.de#67]
If `00` is specified as the month within the year in a date in a HTTP request to the pkgstats API, the response seems to report less total samples and less target samples.

Example:

#### Input without `00`

```
curl -X GET \
'https://pkgstats.archlinux.de/api/packages/libcolord?startMonth=202001&endMonth=202301' \
-H 'accept: application/json'
```

#### Output

```
{"name":"libcolord","samples":294548,"count":881,"popularity":0.3,"startMonth":202001,"endMonth":202301}
```

#### Input with `00`

```
curl -X GET \
'https://pkgstats.archlinux.de/api/packages/libcolord?startMonth=202000&endMonth=202300' \
-H 'accept: application/json'
```

#### Output

```
{"name":"libcolord","samples":294502,"count":855,"popularity":0.29,"startMonth":202000,"endMonth":202300}
```

### What should happen instead?

Maybe just report an error if the month is `00`?

**Comment by pierres** [comment]
Thanks for the hint. I was not able to reproduce the actual issue. Maybe it was caching or I fixed it by accident in the meantime.

However: I made the date validation more strict. (Seems like the builtin Symfony Constraint did not really care if the date was actually a real one)
