### ISSUE TITLE
Many packages get 100% popularity

### ISSUE THREAD

**Issue by PhuNH** [archlinux-de/pkgstats.archlinux.de#74]
Take a look at for example https://pkgstats.archlinux.de/packages or https://pkgstats.archlinux.de/fun

**Comment by pierres** [comment]
Thanks for the hint. There were some deployment issues and cached data got outdated. Fortunately there was no incorrect data stored.

I'll check what can be done to prevent such results in the future.

**Comment by PhuNH** [comment]
Thanks for taking action on this. As I can see, it seems that things have been back to normal.
