### ISSUE TITLE
How to identify a package if Package Search cannot find it?

### ISSUE THREAD

**Issue by PhuNH** [archlinux-de/pkgstats.archlinux.de#75]
I've seen some packages like this but right now I can only remember `basket`: it has some statistics on [pkgstats](https://pkgstats.archlinux.de/api/packages/basket), however there's no result on [Package Search](https://archlinux.org/packages/?sort=&repo=Community&repo=Community-Testing&repo=Core&repo=Extra&repo=KDE-Unstable&repo=Multilib&repo=Multilib-Testing&repo=Testing&q=basket&maintainer=&flagged=). How do I know this is the package that I'm looking for?

**Comment by pierres** [comment]
pkgstats is not limited to offical packages. In this case basket can be found in AUR: https://aur.archlinux.org/packages/basket

In the end we are just handling package names. We cannot know if they came from an official repository, the AUR or what PKGBUILD was used to build it.

**Comment by PhuNH** [comment]
Thanks for your answer, that resolves my issue. I think this can be closed now.
