### ISSUE TITLE
Special Characters remove the webinterface

### ISSUE THREAD

**Issue by mpldr** [archlinux-de/pkgstats.archlinux.de#76]
Entering `{`, `}`, or `|` removes the complete UI. Not a big issue, but for clumsy people correcting the search queries is somewhat of a hazzle this way.

**Comment by pierres** [comment]
Good catch, thanks! I fixed the error handling so it wont crash immediately.

I'll check if it can be done in a more robust way.

**Comment by pierres** [comment]
I have add fixtures and more tests to catch issues earlier.
