### ISSUE TITLE
User tagging

### ISSUE THREAD

**Issue by ghost** [archlinux-de/pkgstats.archlinux.de#78]
Let the users sort the packages into categories with a collaboration system similar to thetvdb.com, musicbrainz, etc. That way instead of the page _Fun statistics_ there would be a search to look for any category and display all packages in that category.

For example, right now if I wanted to see the most used network monitoring tool, I would have to search the internet for the names (_nload_, _speedometer_, _iftop_, _nethogs_) and then copy and paste the names one by one in the search box hoping they have the same names in arch as the packages I've copied. With the proposed feature all this process would be much simpler.

**Comment by m1rm** [comment]
Covered by fun statistics
